# Generated by Django 5.1.6 on 2025-07-21 07:54

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('TECH', 'Technology'), ('PROG', 'Programming'), ('AI', 'Artificial Intelligence'), ('Blockchain', 'Blockchain'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format='JPEG', keep_meta=True, null=True, quality=60, scale=0.5, size=[500, 500], upload_to='blog/profile_images/2025/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[500, 500], upload_to='blog/post_images/2025/'),
        ),
    ]
