# Generated by Django 5.1.6 on 2025-07-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_category_alter_account_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Programming', 'Programming'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Sports', 'Sports'), ('Politics', 'Politics'), ('Economy', 'Economy'), ('Entertainment', 'Entertainment'), ('Other', 'Other')], default='OTHER', max_length=25),
        ),
    ]
